# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/application1/example1/example1.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+protos/application1/example1/example1.proto\"\x1d\n\x08Response\x12\x11\n\thttp_code\x18\x01 \x01(\t\"\x1d\n\x0b\x41\x63\x63\x65ssToken\x12\x0e\n\x06\x61\x63\x63\x65ss\x18\x01 \x01(\t24\n\x0bTestTraffic\x12%\n\nbuild_test\x12\x0c.AccessToken\x1a\t.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.application1.example1.example1_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESPONSE']._serialized_start=47
  _globals['_RESPONSE']._serialized_end=76
  _globals['_ACCESSTOKEN']._serialized_start=78
  _globals['_ACCESSTOKEN']._serialized_end=107
  _globals['_TESTTRAFFIC']._serialized_start=109
  _globals['_TESTTRAFFIC']._serialized_end=161
# @@protoc_insertion_point(module_scope)
